services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - ./backend/mysql.env
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend-container
    env_file:
      - ./backend/backend.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/brgovexpenditures
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    name: app-network
    driver: bridge